### ISSUE TITLE
Need update Python  >= 3.7 

### ISSUE THREAD

**Issue by Nilad** [B-UMMI/seq_typing#23]
In moderne version of python (3.11 in my case), i got some error like this one 

```
Checking dependencies...
/usr/bin/blastn
blastn (2.12.0) found
Traceback (most recent call last):
  File "/usr/local/bin/seq_typing.py", line 33, in <module>
    sys.exit(load_entry_point('seq-typing==2.3', 'console_scripts', 'seq_typing.py')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/seq_typing-2.3-py3.11.egg/seqtyping/seq_typing.py", line 995, in main
    args.func(args)
  File "/usr/local/lib/python3.11/dist-packages/seq_typing-2.3-py3.11.egg/seqtyping/seq_typing.py", line 278, in assembly_subcommand
    run_blast.run_blast(blast_db_path=blast,
  File "/usr/local/lib/python3.11/dist-packages/seq_typing-2.3-py3.11.egg/seqtyping/modules/utils.py", line 200, in wrapper
    results = function(*args, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/seq_typing-2.3-py3.11.egg/seqtyping/modules/run_blast.py", line 329, in run_blast
    _, headers_correspondence = utils.parse_reference(blast_db_path, [])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/seq_typing-2.3-py3.11.egg/seqtyping/modules/utils.py", line 424, in parse_reference
    with open(reference, 'rtU') as reader:
         ^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid mode: 'rtU'
```
This error is common for older script with python version up to 3.7 (https://docs.python.org/3.7/library/functions.html#open)

And a previous error (corrected by a simple and ugly command 'sudo cp -s /usr/bin/python3 /usr/bin/python' ), 'python' for most modern system do not exist anymore and must be remplace by 'python3'

```
Checking dependencies...
/usr/local/lib/python3.11/dist-packages/ReMatCh-4.1.0-py3.11.egg/ReMatCh/src/bowtie2-2.2.9/bowtie2-build
Running: ['/usr/local/lib/python3.11/dist-packages/ReMatCh-4.1.0-py3.11.egg/ReMatCh/src/bowtie2-2.2.9/bowtie2-build', '--version']
STDERR
/usr/bin/env: « python »: Aucun fichier ou dossier de ce type
```

**Comment by ramirma** [comment]
Updated to be compatible with python >= 3.7

**Comment by Coppini** [comment]
@ramirma, just a heads up, it is working up to Python3.10 now, but for Python3.11 (the reported issue), it still fails due to using `rtU` (`U` in read mode was deprecated for Python3.11 as it became the default).
